/**
 * Welder-credit allocation.
 *
 * The reference book states three numbers that must all hold at once: a
 * welder-credit total of 2,476, a per-welder breakdown, and a joint count
 * that the credit total exceeds by ~5.7%. Those constrain the shape of the
 * data — roughly 94% of joints carry a single welder across all four
 * passes and the rest are split-pass — so the seed cannot be generated by
 * picking welders at random and hoping the totals land.
 *
 * Instead we allocate credits directly: each joint is assigned a set of
 * *distinct* welders drawn from a fixed pool of credits, so the per-welder
 * columns sum to the stated figures by construction rather than by luck.
 */

export interface CreditTarget {
  key: string
  /** Joints this welder is credited on. A split-pass joint credits each
   *  welder on it exactly once, never once per pass. */
  credits: number
}

/**
 * Split `total` credits across `joints` groups, each group holding between
 * 1 and `maxPerJoint` distinct welders. Sizes are as even as the totals
 * allow, then the larger groups are placed first so the highest-credit
 * welders drain before the supply of joints runs out.
 */
export function groupSizes(total: number, joints: number, maxPerJoint = 4): number[] {
  if (joints <= 0) return []
  if (total < joints) throw new Error(`cannot place ${total} credits on ${joints} joints`)
  if (total > joints * maxPerJoint) {
    throw new Error(`${total} credits exceeds capacity ${joints * maxPerJoint}`)
  }
  const base = Math.floor(total / joints)
  const larger = total - base * joints
  const sizes = [
    ...Array<number>(larger).fill(base + 1),
    ...Array<number>(joints - larger).fill(base),
  ]
  return sizes.sort((a, b) => b - a)
}

/**
 * Assign distinct welders to each joint so that every welder ends with
 * exactly their target credit count.
 *
 * The greedy rule — always take the welders with the most credits left —
 * is what makes this exact rather than approximate. A welder holding more
 * credits than there are joints remaining can never be satisfied, so
 * spending the largest balances first is precisely the invariant that
 * keeps the allocation feasible to the last joint.
 */
export function allocateCredits(
  targets: CreditTarget[],
  sizes: number[],
): string[][] {
  const remaining = new Map(targets.map((t) => [t.key, t.credits]))
  const total = targets.reduce((s, t) => s + t.credits, 0)
  const capacity = sizes.reduce((s, n) => s + n, 0)
  if (total !== capacity) {
    throw new Error(`credit total ${total} does not match group capacity ${capacity}`)
  }
  for (const t of targets) {
    if (t.credits > sizes.length) {
      throw new Error(`${t.key} needs ${t.credits} joints but only ${sizes.length} exist`)
    }
  }

  const out: string[][] = []
  for (let i = 0; i < sizes.length; i++) {
    const size = sizes[i]!
    const available = [...remaining.entries()]
      .filter(([, n]) => n > 0)
      // Ties broken by key so the allocation is deterministic, not
      // dependent on Map insertion order under a different engine.
      .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))
    if (available.length < size) {
      throw new Error(`joint ${i}: need ${size} distinct welders, ${available.length} have credits left`)
    }
    const chosen = available.slice(0, size).map(([k]) => k)
    for (const k of chosen) remaining.set(k, remaining.get(k)! - 1)
    out.push(chosen)
  }

  const leftover = [...remaining.entries()].filter(([, n]) => n !== 0)
  if (leftover.length) {
    throw new Error(`unspent credits: ${leftover.map(([k, n]) => `${k}=${n}`).join(', ')}`)
  }
  return out
}

/**
 * Spread one welder set across the four passes (Root/Hot/Fill/Cap).
 *
 * A single-welder joint runs all four passes; a two-welder joint splits
 * root+hot from fill+cap, which is how `CT/CT/HS2/HS2` reads in the source
 * log. Larger sets fill passes in order and then repeat the last welder.
 */
export function assignPasses(welderKeys: string[]): [string, string, string, string] {
  const n = welderKeys.length
  if (n === 1) {
    const k = welderKeys[0]!
    return [k, k, k, k]
  }
  if (n === 2) {
    const [a, b] = welderKeys as [string, string]
    return [a, a, b, b]
  }
  if (n === 3) {
    const [a, b, c] = welderKeys as [string, string, string]
    return [a, b, c, c]
  }
  return [welderKeys[0]!, welderKeys[1]!, welderKeys[2]!, welderKeys[3]!]
}
