/**
 * The SQL template seed is generated from the TypeScript checklist. This
 * re-checks the invariant, so a hand-edit to the migration that drifts from
 * the module — or a checklist change without regenerating — fails here
 * rather than showing up as a wrong percentage months later.
 */
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import {
  buildTemplateSections, FLOWLINE_WEIGHTS, MASTER_CHECKLIST,
} from '@/lib/domain/checklist'

const sql = readFileSync('supabase/migrations/0004_seed_templates.sql', 'utf8')

describe('checklist parity between TypeScript and SQL', () => {
  it('carries every flowline section title verbatim into the migration', () => {
    for (const s of buildTemplateSections('flowline', 'tpl')) {
      expect(sql, `section ${s.sectionNumber} missing from the migration`)
        .toContain(s.title.replace(/'/g, "''"))
    }
  })

  it('carries every facility section title too', () => {
    for (const s of buildTemplateSections('facility', 'tpl')) {
      expect(sql).toContain(s.title.replace(/'/g, "''"))
    }
  })

  it('is regenerated, not hand-edited', () => {
    expect(sql).toContain('GENERATED by scripts/gen-template-migration.ts')
  })
})

describe('weights', () => {
  it('sums to 100 across the flowline scoring sections', () => {
    const total = buildTemplateSections('flowline', 'tpl').reduce((s, x) => s + x.weight, 0)
    expect(total).toBe(100)
  })

  it('sums to 100 across the facility scoring sections', () => {
    const total = buildTemplateSections('facility', 'tpl').reduce((s, x) => s + x.weight, 0)
    expect(total).toBe(100)
  })

  it('gives the generated checklist section no weight', () => {
    expect(FLOWLINE_WEIGHTS['1']).toBe(0)
  })

  it('gives the derived overview sheet no independent weight', () => {
    expect(FLOWLINE_WEIGHTS['11']).toBe(0)
  })

  it('puts the most weight on the weld log and the MTRs', () => {
    const ranked = Object.entries(FLOWLINE_WEIGHTS).sort((a, b) => b[1] - a[1])
    expect(ranked[0]![0]).toBe('12')
    expect(ranked[1]![0]).toBe('15')
  })

  it('makes supplemental sections weightless so real-world extras cannot distort the score', () => {
    const supplemental = buildTemplateSections('flowline', 'tpl').filter((s) => s.isSupplemental)
    expect(supplemental.length).toBeGreaterThan(0)
    expect(supplemental.every((s) => s.weight === 0)).toBe(true)
  })
})

describe('the checklist itself', () => {
  it('has 22 sections', () => {
    expect(MASTER_CHECKLIST).toHaveLength(22)
  })

  it('marks 19 through 22 as facility-only', () => {
    for (const n of ['19', '20', '21', '22']) {
      expect(MASTER_CHECKLIST.find((e) => e.sectionNumber === n)!.appliesTo).toBe('facility')
    }
  })
})
