-- Remove every demo row. Generated by scripts/seed-demo.ts.
--
-- Safe by construction: every demo id begins 'd0d0d0d0-', which no row
-- created through the application can have — application ids come from
-- gen_random_uuid(), and the odds of it producing this prefix are 1 in
-- 4 billion per row. Nothing here can touch a real book.
--
-- Deleted child-first so no foreign key is left dangling. The audit trail
-- is NOT deleted: it is append-only by design, and the record that these
-- books existed and were removed is exactly what an append-only trail is
-- for.
begin;
-- job_assignment is keyed on (job_book_id, user_id) and carries no id of
-- its own, so it is removed by the books it points at.
delete from job_assignment where job_book_id::text like 'd0d0d0d0-%' or user_id::text like 'd0d0d0d0-%';
-- Same for completeness_certification, whose primary key IS the book.
delete from completeness_certification where job_book_id::text like 'd0d0d0d0-%';
delete from compliance_flag where id::text like 'd0d0d0d0-%';
delete from gate_condition where id::text like 'd0d0d0d0-%';
delete from gate_review where id::text like 'd0d0d0d0-%';
delete from weld where id::text like 'd0d0d0d0-%';
delete from torque_connection where id::text like 'd0d0d0d0-%';
delete from nde_report_line where id::text like 'd0d0d0d0-%';
delete from nde_report where id::text like 'd0d0d0d0-%';
delete from material_heat where id::text like 'd0d0d0d0-%';
delete from pressure_test where id::text like 'd0d0d0d0-%';
delete from cp_test_point where id::text like 'd0d0d0d0-%';
delete from ut_reading where id::text like 'd0d0d0d0-%';
delete from coating_inspection where id::text like 'd0d0d0d0-%';
delete from document where id::text like 'd0d0d0d0-%';
delete from weld_line where id::text like 'd0d0d0d0-%';
delete from certificate where id::text like 'd0d0d0d0-%';
delete from welder_qualification where id::text like 'd0d0d0d0-%';
delete from welder where id::text like 'd0d0d0d0-%';
delete from cwi where id::text like 'd0d0d0d0-%';
delete from ndt_technician where id::text like 'd0d0d0d0-%';
delete from torque_wrench where id::text like 'd0d0d0d0-%';
delete from timeliness_period where id::text like 'd0d0d0d0-%';
delete from job_book_section where id::text like 'd0d0d0d0-%';
delete from inspector_grant where id::text like 'd0d0d0d0-%';
delete from audit_finding where id::text like 'd0d0d0d0-%';
delete from job_book_audit where id::text like 'd0d0d0d0-%';
delete from job_book where id::text like 'd0d0d0d0-%';
delete from project where id::text like 'd0d0d0d0-%';
delete from client_org where id::text like 'd0d0d0d0-%';
delete from app_user where id::text like 'd0d0d0d0-%';
commit;
