/**
 * Bundle every migration into one file to paste into the Supabase SQL
 * editor.
 *
 * Eleven files pasted in order is eleven chances to paste them out of
 * order, and a later file alters tables an earlier one creates — so a
 * mis-ordered run fails halfway and leaves a half-built schema that is
 * worse than none. One file removes the opportunity.
 *
 * Generated, never edited: `supabase/migrations/` stays the source of
 * truth, and `npm run build:setup` regenerates this whenever a migration
 * is added. The header records which files went in, so a bundle can be
 * checked against the repository it came from.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const DIR = 'supabase/migrations'
const OUT = 'supabase/setup.sql'

const files = readdirSync(DIR).filter((f) => f.endsWith('.sql')).sort()

const header = `-- ---------------------------------------------------------------------
-- Fortress Job Book Tracker — complete schema.
--
-- GENERATED by \`npm run build:setup\` from ${DIR}/. Do not edit this file;
-- edit the migration and regenerate, or the two will disagree and the one
-- that ran will not be the one in the repository.
--
-- Paste the whole thing into the Supabase SQL editor and run it once, on a
-- new project. It is the same statements \`npm run verify:db\` applies to a
-- throwaway Postgres before asserting the database's guarantees.
--
-- Files, in order:
${files.map((f, i) => `--   ${String(i + 1).padStart(2)}. ${f}`).join('\n')}
--
-- Generated ${new Date().toISOString().slice(0, 10)}.
-- ---------------------------------------------------------------------

`

const body = files.map((f) => {
  const sql = readFileSync(join(DIR, f), 'utf8').trimEnd()
  return `\n-- ═══════════════════════════════════════════════════════════════════\n` +
         `-- ${f}\n` +
         `-- ═══════════════════════════════════════════════════════════════════\n\n` +
         `${sql}\n`
}).join('\n')

const footer = `

-- ---------------------------------------------------------------------
-- Done. What you should see:
--
--   · 32 tables, every one with Row Level Security enabled and FORCED
--   · a private storage bucket named 'job-book-documents'
--   · both book templates, with all 22 checklist sections each
--
-- Check with:
--
--   select count(*) filter (where rowsecurity) as rls_on,
--          count(*) as tables
--     from pg_tables where schemaname = 'public';
--
--   select id, public from storage.buckets where id = 'job-book-documents';
--
--   select bt.book_type, count(*) as sections
--     from section_definition sd
--     join book_template bt on bt.id = sd.book_template_id
--    group by bt.book_type;
--
-- Then create the first admin — nobody can invite anyone until one exists:
--
--   insert into app_user (email, full_name, role)
--   values ('you@fortressds.com', 'Your Name', 'fortress_admin');
-- ---------------------------------------------------------------------
`

writeFileSync(OUT, header + body + footer)
const lines = (header + body + footer).split('\n').length
console.log(`${OUT} — ${files.length} migrations, ${lines} lines`)
