/**
 * Emits `supabase/migrations/0004_seed_templates.sql` from the checklist
 * module, so the SQL template rows and the TypeScript checklist can never
 * drift apart. `src/test/checklist-parity.test.ts` re-checks the invariant.
 */
import { writeFileSync } from 'node:fs'
import { buildTemplateSections } from '../src/lib/domain/checklist'

const q = (s: string | null) => (s === null ? 'null' : `'${s.replace(/'/g, "''")}'`)

const chunks: string[] = [
  `-- =====================================================================`,
  `-- Section templates, v1.`,
  `-- GENERATED by scripts/gen-template-migration.ts from`,
  `-- src/lib/domain/checklist.ts. Edit the checklist module and re-run;`,
  `-- do not hand-edit this file.`,
  `-- =====================================================================`,
  ``,
]

for (const bookType of ['flowline', 'facility'] as const) {
  const tplVar = `v_${bookType}_tpl`
  const sections = buildTemplateSections(bookType, 'TPL')
  const total = sections.reduce((s, x) => s + x.weight, 0)
  chunks.push(
    `do $$`,
    `declare ${tplVar} uuid;`,
    `begin`,
    `  insert into book_template (book_type, version, effective_date, is_active)`,
    `  values ('${bookType}', 1, date '2026-01-01', true)`,
    `  returning id into ${tplVar};`,
    ``,
    `  -- Weights sum to ${total} across scoring sections.`,
    `  insert into section_definition`,
    `    (book_template_id, section_number, sort_order, title, applies_to, weight,`,
    `     requirement_type, min_documents, linked_record_type, is_required,`,
    `     is_supplemental, notes)`,
    `  values`,
  )
  const rows = sections.map(
    (s) =>
      `    (${tplVar}, ${q(s.sectionNumber)}, ${s.sortOrder}, ${q(s.title)}, ` +
      `'${s.appliesTo}', ${s.weight}, '${s.requirementType}', ${s.minDocuments}, ` +
      `${q(s.linkedRecordType ?? null)}, ${s.isRequired}, ${s.isSupplemental}, ` +
      `${q(s.notes ?? null)})`,
  )
  chunks.push(rows.join(',\n') + ';', `end $$;`, ``)
}

writeFileSync('supabase/migrations/0004_seed_templates.sql', chunks.join('\n'))
console.log('wrote supabase/migrations/0004_seed_templates.sql')
