/**
 * The governing checklist.
 *
 * Section titles are transcribed verbatim from `Job Book Checklist
 * Edited.pdf`, including its original phrasing, because the operator audits
 * against these exact strings. Do not reword them in UI or exports.
 *
 * The list is data, not code paths: adding the facility checklist when it
 * arrives is a new template row set, not a migration. Nothing downstream
 * branches on the literal string "flowline".
 */

import type { AppliesTo, BookType, RequirementType, SectionDefinition } from './types'

export interface ChecklistEntry {
  sectionNumber: string
  title: string
  appliesTo: AppliesTo
  requirementType: RequirementType
  linkedRecordType?: string
  minDocuments?: number
  isSupplemental?: boolean
  notes?: string
}

/** Sections 1–22 of the master checklist, in checklist order. */
export const MASTER_CHECKLIST: ChecklistEntry[] = [
  { sectionNumber: '1',  title: 'Job Book Checklist',
    appliesTo: 'both', requirementType: 'document',
    notes: 'Generated by the application from live status; carries no weight.' },
  { sectionNumber: '2',  title: 'Facility / Flow Line Overview',
    appliesTo: 'both', requirementType: 'document', minDocuments: 2,
    notes: 'Drawing set — original plus redline.' },
  { sectionNumber: '3',  title: 'Noble Energy Piping Specification',
    appliesTo: 'both', requirementType: 'document',
    notes: 'Current revision.' },
  { sectionNumber: '4',  title: 'Welding Procedure Specification (WPS)',
    appliesTo: 'both', requirementType: 'document' },
  { sectionNumber: '5',  title: 'Welding Procedure Qualification Record (PQR)',
    appliesTo: 'both', requirementType: 'document' },
  { sectionNumber: '6',  title: 'Welder Performance Qualifications (WPQ)',
    appliesTo: 'both', requirementType: 'personnel_certs', linkedRecordType: 'welder' },
  { sectionNumber: '7',  title: 'Certified Welding Inspector Credentials',
    appliesTo: 'both', requirementType: 'personnel_certs', linkedRecordType: 'cwi' },
  { sectionNumber: '8',  title: 'Non-Destructive Testing Technician Credentials',
    appliesTo: 'both', requirementType: 'personnel_certs', linkedRecordType: 'ndt_technician' },
  { sectionNumber: '9',  title: 'Non-Destructive Testing Procedures',
    appliesTo: 'both', requirementType: 'document', minDocuments: 4,
    notes: 'One procedure per method in use: MT, PT, RT, UT.' },
  { sectionNumber: '10', title: 'NDT Job Logs and Films',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'nde_report',
    notes: 'Films provided separately.' },
  { sectionNumber: '11', title: 'Weld Log Overview Sheet with Inspection Percentages (Noble Template)',
    appliesTo: 'both', requirementType: 'derived', linkedRecordType: 'weld',
    notes: 'Rolls up section 12; never scored independently.' },
  { sectionNumber: '12', title: 'Detailed Weld Log (Noble Template)',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'weld' },
  { sectionNumber: '13', title: 'Torque Wrench Calibration Certificates',
    appliesTo: 'both', requirementType: 'equipment_certs', linkedRecordType: 'torque_wrench' },
  { sectionNumber: '14', title: 'Detailed Torque Log (Noble Template)',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'torque_connection' },
  { sectionNumber: '15', title: 'Material Test Reports',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'material_heat',
    notes: 'One MTR per heat number referenced by any weld.' },
  { sectionNumber: '16', title: 'Pressure Testing Procedure with P&ID Valve Orientation',
    appliesTo: 'both', requirementType: 'document' },
  { sectionNumber: '17', title: 'Pressure Testing Results with Recorder Calibration Certificates',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'pressure_test' },
  { sectionNumber: '18', title: 'Cathodic Protection Testing Locations and Baseline Results',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'cp_test_point' },
  { sectionNumber: '19', title: 'Ultrasonic Testing Locations and Baseline Results',
    appliesTo: 'facility', requirementType: 'records', linkedRecordType: 'ut_reading' },
  { sectionNumber: '20', title: 'As-Built P&IDs',
    appliesTo: 'facility', requirementType: 'document' },
  { sectionNumber: '21', title: 'Isometric Weld and X-Ray Map',
    appliesTo: 'facility', requirementType: 'document' },
  { sectionNumber: '22', title: 'Isometric Heat Number and Torque Map',
    appliesTo: 'facility', requirementType: 'document' },
]

/**
 * Flowline books supply sections 19–22 as one combined deliverable. This is
 * a template variant, not a special case in the scoring code: the flowline
 * template simply carries this row instead of 19–22.
 */
export const FLOWLINE_COMBINED_MAP: ChecklistEntry = {
  sectionNumber: '19-22',
  title: 'Weld Map with X-ray, Heat Number, and Torque Map',
  appliesTo: 'flowline',
  requirementType: 'document',
  minDocuments: 1,
  notes: 'Flowline equivalent of facility sections 19–22, delivered combined.',
}

/**
 * Suggested starting weights for a flowline book (§5.3), summing to 100.
 * Stored as template configuration and editable per §9; these are the
 * seeded defaults, and the template version pins them so a score computed
 * last quarter reproduces exactly.
 */
export const FLOWLINE_WEIGHTS: Record<string, number> = {
  '1': 0,       // generated by the app
  '2': 3,
  '3': 1,
  '4': 0.5,
  '5': 0.5,
  '6': 6,
  '7': 2,
  '8': 3,
  '9': 2,
  '10': 10,     // 40 NDE reports
  '11': 0,      // derived from 12
  '12': 20,     // largest data volume, highest audit exposure
  '13': 5,
  '14': 12,     // 616 connections
  '15': 15,     // 189 documents; traceability backbone
  '16': 1,
  '17': 8,      // acceptance gate
  '18': 5,
  '19-22': 6,   // combined weld / x-ray / heat / torque map
}

/**
 * Facility weights. The facility checklist itself is not yet published, so
 * these mirror the flowline weights and redistribute the combined map's 6
 * points across the four separate map/drawing sections. Revisit with the
 * QA/QC managers when the real checklist lands; the schema needs no change.
 */
export const FACILITY_WEIGHTS: Record<string, number> = {
  '1': 0, '2': 3, '3': 1, '4': 0.5, '5': 0.5, '6': 6, '7': 2, '8': 3, '9': 2,
  '10': 10, '11': 0, '12': 20, '13': 5, '14': 12, '15': 15, '16': 1, '17': 8,
  '18': 5,
  '19': 2,   // UT baselines
  '20': 2,   // as-built P&IDs
  '21': 1,   // isometric weld & x-ray map
  '22': 1,   // isometric heat number & torque map
}

/**
 * Non-scoring sections for real-world extras that appear in no checklist —
 * DP452 shipped 14 sequential Flexpipe daily field reports. They get a home
 * without distorting the percentage.
 */
export const SUPPLEMENTAL_SECTIONS: ChecklistEntry[] = [
  { sectionNumber: 'S1', title: 'Flexpipe Daily Field Reports',
    appliesTo: 'both', requirementType: 'supplemental', isSupplemental: true,
    notes: 'Delivered in DP452; appears on no checklist revision.' },
]

/**
 * Build the section-definition rows for one book type and template version.
 *
 * All 22 checklist sections are scaffolded for both book types, including
 * the ones that do not apply: a flowline book shows sections 19–22 marked
 * N/A rather than omitting them, so an operator can see they were
 * considered and ruled out rather than forgotten. An N/A section leaves
 * both sides of the division, so its presence cannot move the score.
 */
export function buildTemplateSections(
  bookType: 'flowline' | 'facility',
  bookTemplateId: string,
): SectionDefinition[] {
  const weights = bookType === 'flowline' ? FLOWLINE_WEIGHTS : FACILITY_WEIGHTS
  const entries: ChecklistEntry[] = MASTER_CHECKLIST
    .concat(bookType === 'flowline' ? [FLOWLINE_COMBINED_MAP] : [])
    .concat(SUPPLEMENTAL_SECTIONS)

  return entries.map((e, i) => ({
    id: `${bookTemplateId}:${e.sectionNumber}`,
    bookTemplateId,
    sectionNumber: e.sectionNumber,
    sortOrder: i + 1,
    title: e.title,
    appliesTo: e.appliesTo,
    // A section that does not apply to this book type carries no weight,
    // whatever the weight map says.
    weight: e.isSupplemental || !appliesToBook(e.appliesTo, bookType)
      ? 0
      : (weights[e.sectionNumber] ?? 0),
    requirementType: e.requirementType,
    minDocuments: e.minDocuments ?? 1,
    linkedRecordType: e.linkedRecordType ?? null,
    isRequired: !e.isSupplemental,
    isSupplemental: e.isSupplemental ?? false,
    notes: e.notes ?? null,
  }))
}

/** Does a checklist entry apply to this book type? */
export function appliesToBook(appliesTo: AppliesTo, bookType: BookType): boolean {
  return appliesTo === 'both' || appliesTo === bookType
}

/**
 * Sections scaffolded but not applicable to this book type. The scaffolder
 * marks these N/A on creation, with the reason recorded, so nothing is
 * silently absent from the checklist the operator audits against.
 */
export function notApplicableSectionNumbers(bookType: BookType): string[] {
  return MASTER_CHECKLIST
    .filter((e) => !appliesToBook(e.appliesTo, bookType))
    .map((e) => e.sectionNumber)
}
