/**
 * The governing checklist.
 *
 * Section titles are transcribed verbatim from Appendix A of FDS-JBMP-001,
 * which reproduces them as the governing client checklist states them. The
 * operator audits against these exact strings. Do not reword them in UI or
 * exports.
 *
 * They are operator-neutral on purpose. The delivered books carried "Noble
 * Energy Piping Specification" and "(Noble Template)" in four titles while
 * the specification actually on file had moved to Chevron at a later
 * revision — §3 of the program calls that out as "a finding waiting to
 * happen". Which document is in force is a recorded field on the job book
 * (`pipingSpecReference` and its revision), confirmed with the client at
 * Gate 0, not a word baked into a section title where nobody can update
 * it.
 *
 * The list is data, not code paths: adding the facility checklist when it
 * arrives is a new template row set, not a migration. Nothing downstream
 * branches on the literal string "flowline".
 */

import type { AppliesTo, BookType, RequirementType, SectionDefinition } from './types'

export interface ChecklistEntry {
  sectionNumber: string
  title: string
  appliesTo: AppliesTo
  requirementType: RequirementType
  linkedRecordType?: string
  minDocuments?: number
  isSupplemental?: boolean
  /** Off-checklist but scored when a job enables it. */
  isOptional?: boolean
  notes?: string
}

/** Sections 1–22 of the master checklist, in checklist order. */
export const MASTER_CHECKLIST: ChecklistEntry[] = [
  { sectionNumber: '1',  title: 'Job Book Checklist',
    appliesTo: 'both', requirementType: 'document',
    notes: 'Generated by the application from live status; carries no weight.' },
  { sectionNumber: '2',  title: 'Facility / Flow Line Overview',
    appliesTo: 'both', requirementType: 'document', minDocuments: 2,
    notes: 'Drawing set — original plus redline.' },
  { sectionNumber: '3',  title: 'Operator Piping Specification',
    appliesTo: 'both', requirementType: 'document',
    notes: 'Current revision.' },
  { sectionNumber: '4',  title: 'Welding Procedure Specification (WPS)',
    appliesTo: 'both', requirementType: 'document' },
  { sectionNumber: '5',  title: 'Welding Procedure Qualification Record (PQR)',
    appliesTo: 'both', requirementType: 'document' },
  { sectionNumber: '6',  title: 'Welder Performance Qualifications (WPQ)',
    appliesTo: 'both', requirementType: 'personnel_certs', linkedRecordType: 'welder' },
  { sectionNumber: '7',  title: 'Certified Welding Inspector Credentials',
    appliesTo: 'both', requirementType: 'personnel_certs', linkedRecordType: 'cwi' },
  { sectionNumber: '8',  title: 'Non-Destructive Testing Technician Credentials',
    appliesTo: 'both', requirementType: 'personnel_certs', linkedRecordType: 'ndt_technician' },
  { sectionNumber: '9',  title: 'Non-Destructive Testing Procedures',
    appliesTo: 'both', requirementType: 'document', minDocuments: 4,
    notes: 'One procedure per method in use: MT, PT, RT, UT.' },
  { sectionNumber: '10', title: 'NDT Job Logs and Films',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'nde_report',
    notes: 'Films provided separately.' },
  { sectionNumber: '11', title: 'Weld Log Overview Sheet with Inspection Percentages',
    appliesTo: 'both', requirementType: 'derived', linkedRecordType: 'weld',
    notes: 'Rolls up section 12; never scored independently.' },
  { sectionNumber: '12', title: 'Detailed Weld Log',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'weld' },
  { sectionNumber: '13', title: 'Torque Wrench Calibration Certificates',
    appliesTo: 'both', requirementType: 'equipment_certs', linkedRecordType: 'torque_wrench' },
  { sectionNumber: '14', title: 'Detailed Torque Log',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'torque_connection' },
  { sectionNumber: '15', title: 'Material Test Reports',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'material_heat',
    notes: 'One MTR per heat number referenced by any weld.' },
  { sectionNumber: '16', title: 'Pressure Testing Procedure with P&ID Valve Orientation',
    appliesTo: 'both', requirementType: 'document' },
  { sectionNumber: '17', title: 'Pressure Testing Results with Recorder Calibration Certificates',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'pressure_test' },
  { sectionNumber: '18', title: 'Cathodic Protection Testing Locations and Baseline Results',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'cp_test_point' },
  { sectionNumber: '19', title: 'Ultrasonic Testing Locations and Baseline Results',
    appliesTo: 'facility', requirementType: 'records', linkedRecordType: 'ut_reading' },
  { sectionNumber: '20', title: 'As-Built P&IDs',
    appliesTo: 'facility', requirementType: 'document' },
  { sectionNumber: '21', title: 'Isometric Weld and X-Ray Map',
    appliesTo: 'facility', requirementType: 'records', linkedRecordType: 'isometric',
    notes: 'One drawing per isometric referenced by either log.' },
  { sectionNumber: '22', title: 'Isometric Heat Number and Torque Map',
    appliesTo: 'facility', requirementType: 'records', linkedRecordType: 'isometric',
    notes: 'One drawing per isometric referenced by either log.' },
]

/**
 * Flowline books supply sections 19–22 as one combined deliverable. This is
 * a template variant, not a special case in the scoring code: the flowline
 * template simply carries this row instead of 19–22.
 */
export const FLOWLINE_COMBINED_MAP: ChecklistEntry = {
  sectionNumber: '19-22',
  title: 'Weld Map with X-ray, Heat Number, and Torque Map',
  appliesTo: 'flowline',
  requirementType: 'document',
  minDocuments: 1,
  notes: 'Flowline equivalent of facility sections 19–22, delivered combined.',
}

/**
 * Sections that appear on no revision of the governing checklist but are
 * real deliverables on some jobs, scored when the job enables them.
 *
 * This is not the same as a supplemental section. A supplemental section
 * is never scored — it is a home for documents that arrived without a
 * category. An optional section carries genuine weight when enabled and
 * leaves the denominator entirely when not, so enabling it can lower a
 * book's percentage and disabling it can never raise one artificially.
 */
export const OPTIONAL_SECTIONS: ChecklistEntry[] = [
  { sectionNumber: '23', title: 'Coating Inspection',
    appliesTo: 'both', requirementType: 'records', linkedRecordType: 'coating_inspection',
    isOptional: true,
    notes: 'Off-checklist. Scored per construction area when enabled for a job.' },
]

/**
 * Suggested starting weights for a flowline book (§5.3), summing to 100.
 * Stored as template configuration and editable per §9; these are the
 * seeded defaults, and the template version pins them so a score computed
 * last quarter reproduces exactly.
 */
export const FLOWLINE_WEIGHTS: Record<string, number> = {
  '1': 0,       // generated by the app
  '2': 3,
  '3': 1,
  '4': 0.5,
  '5': 0.5,
  '6': 6,
  '7': 2,
  '8': 3,
  '9': 2,
  '10': 10,     // 40 NDE reports
  '11': 0,      // derived from 12
  '12': 20,     // largest data volume, highest audit exposure
  '13': 5,
  '14': 12,     // 616 connections
  '15': 15,     // 189 documents; traceability backbone
  '16': 1,
  '17': 8,      // acceptance gate
  '18': 5,
  '19-22': 6,   // combined weld / x-ray / heat / torque map
}

/**
 * Facility weights, v1 — placeholders written before any facility
 * checklist was available. Kept because templates are versioned and a
 * score computed under v1 must stay reproducible; superseded by v2 below
 * for new books.
 */
export const FACILITY_WEIGHTS_V1: Record<string, number> = {
  '1': 0, '2': 3, '3': 1, '4': 0.5, '5': 0.5, '6': 6, '7': 2, '8': 3, '9': 2,
  '10': 10, '11': 0, '12': 20, '13': 5, '14': 12, '15': 15, '16': 1, '17': 8,
  '18': 5, '19': 2, '20': 2, '21': 1, '22': 1,
}

/**
 * Facility weights, v2 — the set supplied with the Greeley Crescent
 * reference figures. Sums to 100 including the optional section 23.
 *
 * These differ substantially from the flowline weights, and the shift is
 * the interesting part: a facility book's isometric map sections carry 10
 * points each against the flowline book's 6 for all four combined, while
 * the weld log drops from 20 to 14. Facility turnover is judged more on
 * drawing coverage and less on weld volume.
 *
 * Section 23's 4 points count only when a job enables it; a job that does
 * not is scored over the remaining 96.
 */
export const FACILITY_WEIGHTS: Record<string, number> = {
  '1': 0,      // generated by the app
  '2': 2,
  '3': 0.5,
  '4': 0.25,
  '5': 0.25,
  '6': 3,
  '7': 0.5,
  '8': 1,
  '9': 0.5,
  '10': 7,
  '11': 0,     // derived from 12
  '12': 14,
  '13': 3,
  '14': 8,
  '15': 12,
  '16': 1,
  '17': 10,
  '18': 4,
  '19': 4,
  '20': 5,
  '21': 10,    // isometric weld & x-ray map
  '22': 10,    // isometric heat number & torque map
  '23': 4,     // coating inspection — optional
}

/**
 * Non-scoring sections for real-world extras that appear in no checklist —
 * DP452 shipped 14 sequential Flexpipe daily field reports. They get a home
 * without distorting the percentage.
 */
export const SUPPLEMENTAL_SECTIONS: ChecklistEntry[] = [
  { sectionNumber: 'S1', title: 'Flexpipe Daily Field Reports',
    appliesTo: 'both', requirementType: 'supplemental', isSupplemental: true,
    notes: 'Delivered in DP452; appears on no checklist revision.' },
]

/**
 * Build the section-definition rows for one book type and template version.
 *
 * All 22 checklist sections are scaffolded for both book types, including
 * the ones that do not apply: a flowline book shows sections 19–22 marked
 * N/A rather than omitting them, so an operator can see they were
 * considered and ruled out rather than forgotten. An N/A section leaves
 * both sides of the division, so its presence cannot move the score.
 */
export function buildTemplateSections(
  bookType: 'flowline' | 'facility',
  bookTemplateId: string,
): SectionDefinition[] {
  const weights = bookType === 'flowline' ? FLOWLINE_WEIGHTS : FACILITY_WEIGHTS
  const entries: ChecklistEntry[] = MASTER_CHECKLIST
    .concat(bookType === 'flowline' ? [FLOWLINE_COMBINED_MAP] : [])
    .concat(OPTIONAL_SECTIONS)
    .concat(SUPPLEMENTAL_SECTIONS)

  return entries.map((e, i) => ({
    id: `${bookTemplateId}:${e.sectionNumber}`,
    bookTemplateId,
    sectionNumber: e.sectionNumber,
    sortOrder: i + 1,
    title: e.title,
    appliesTo: e.appliesTo,
    // A section that does not apply to this book type carries no weight,
    // whatever the weight map says.
    weight: e.isSupplemental || !appliesToBook(e.appliesTo, bookType)
      ? 0
      : (weights[e.sectionNumber] ?? 0),
    requirementType: e.requirementType,
    minDocuments: e.minDocuments ?? 1,
    linkedRecordType: e.linkedRecordType ?? null,
    isRequired: !e.isSupplemental && !e.isOptional,
    isSupplemental: e.isSupplemental ?? false,
    isOptional: e.isOptional ?? false,
    notes: e.notes ?? null,
  }))
}

/** Does a checklist entry apply to this book type? */
export function appliesToBook(appliesTo: AppliesTo, bookType: BookType): boolean {
  return appliesTo === 'both' || appliesTo === bookType
}

/**
 * Sections scaffolded but not applicable to this book type. The scaffolder
 * marks these N/A on creation, with the reason recorded, so nothing is
 * silently absent from the checklist the operator audits against.
 */
export function notApplicableSectionNumbers(bookType: BookType): string[] {
  return MASTER_CHECKLIST
    .filter((e) => !appliesToBook(e.appliesTo, bookType))
    .map((e) => e.sectionNumber)
}
