-- =====================================================================
-- Section templates, v1.
-- GENERATED by scripts/gen-template-migration.ts from
-- src/lib/domain/checklist.ts. Edit the checklist module and re-run;
-- do not hand-edit this file.
-- =====================================================================

do $$
declare v_flowline_tpl uuid;
begin
  insert into book_template (book_type, version, effective_date, is_active)
  values ('flowline', 1, date '2026-01-01', true)
  returning id into v_flowline_tpl;

  -- Weights sum to 100 across scoring sections.
  insert into section_definition
    (book_template_id, section_number, sort_order, title, applies_to, weight,
     requirement_type, min_documents, linked_record_type, is_required,
     is_supplemental, notes)
  values
    (v_flowline_tpl, '1', 1, 'Job Book Checklist', 'both', 0, 'document', 1, null, true, false, 'Generated by the application from live status; carries no weight.'),
    (v_flowline_tpl, '2', 2, 'Facility / Flow Line Overview', 'both', 3, 'document', 2, null, true, false, 'Drawing set — original plus redline.'),
    (v_flowline_tpl, '3', 3, 'Noble Energy Piping Specification', 'both', 1, 'document', 1, null, true, false, 'Current revision.'),
    (v_flowline_tpl, '4', 4, 'Welding Procedure Specification (WPS)', 'both', 0.5, 'document', 1, null, true, false, null),
    (v_flowline_tpl, '5', 5, 'Welding Procedure Qualification Record (PQR)', 'both', 0.5, 'document', 1, null, true, false, null),
    (v_flowline_tpl, '6', 6, 'Welder Performance Qualifications (WPQ)', 'both', 6, 'personnel_certs', 1, 'welder', true, false, null),
    (v_flowline_tpl, '7', 7, 'Certified Welding Inspector Credentials', 'both', 2, 'personnel_certs', 1, 'cwi', true, false, null),
    (v_flowline_tpl, '8', 8, 'Non-Destructive Testing Technician Credentials', 'both', 3, 'personnel_certs', 1, 'ndt_technician', true, false, null),
    (v_flowline_tpl, '9', 9, 'Non-Destructive Testing Procedures', 'both', 2, 'document', 4, null, true, false, 'One procedure per method in use: MT, PT, RT, UT.'),
    (v_flowline_tpl, '10', 10, 'NDT Job Logs and Films', 'both', 10, 'records', 1, 'nde_report', true, false, 'Films provided separately.'),
    (v_flowline_tpl, '11', 11, 'Weld Log Overview Sheet with Inspection Percentages (Noble Template)', 'both', 0, 'derived', 1, 'weld', true, false, 'Rolls up section 12; never scored independently.'),
    (v_flowline_tpl, '12', 12, 'Detailed Weld Log (Noble Template)', 'both', 20, 'records', 1, 'weld', true, false, null),
    (v_flowline_tpl, '13', 13, 'Torque Wrench Calibration Certificates', 'both', 5, 'equipment_certs', 1, 'torque_wrench', true, false, null),
    (v_flowline_tpl, '14', 14, 'Detailed Torque Log (Noble Template)', 'both', 12, 'records', 1, 'torque_connection', true, false, null),
    (v_flowline_tpl, '15', 15, 'Material Test Reports', 'both', 15, 'records', 1, 'material_heat', true, false, 'One MTR per heat number referenced by any weld.'),
    (v_flowline_tpl, '16', 16, 'Pressure Testing Procedure with P&ID Valve Orientation', 'both', 1, 'document', 1, null, true, false, null),
    (v_flowline_tpl, '17', 17, 'Pressure Testing Results with Recorder Calibration Certificates', 'both', 8, 'records', 1, 'pressure_test', true, false, null),
    (v_flowline_tpl, '18', 18, 'Cathodic Protection Testing Locations and Baseline Results', 'both', 5, 'records', 1, 'cp_test_point', true, false, null),
    (v_flowline_tpl, '19', 19, 'Ultrasonic Testing Locations and Baseline Results', 'facility', 0, 'records', 1, 'ut_reading', true, false, null),
    (v_flowline_tpl, '20', 20, 'As-Built P&IDs', 'facility', 0, 'document', 1, null, true, false, null),
    (v_flowline_tpl, '21', 21, 'Isometric Weld and X-Ray Map', 'facility', 0, 'document', 1, null, true, false, null),
    (v_flowline_tpl, '22', 22, 'Isometric Heat Number and Torque Map', 'facility', 0, 'document', 1, null, true, false, null),
    (v_flowline_tpl, '19-22', 23, 'Weld Map with X-ray, Heat Number, and Torque Map', 'flowline', 6, 'document', 1, null, true, false, 'Flowline equivalent of facility sections 19–22, delivered combined.'),
    (v_flowline_tpl, 'S1', 24, 'Flexpipe Daily Field Reports', 'both', 0, 'supplemental', 1, null, false, true, 'Delivered in DP452; appears on no checklist revision.');
end $$;

do $$
declare v_facility_tpl uuid;
begin
  insert into book_template (book_type, version, effective_date, is_active)
  values ('facility', 1, date '2026-01-01', true)
  returning id into v_facility_tpl;

  -- Weights sum to 100 across scoring sections.
  insert into section_definition
    (book_template_id, section_number, sort_order, title, applies_to, weight,
     requirement_type, min_documents, linked_record_type, is_required,
     is_supplemental, notes)
  values
    (v_facility_tpl, '1', 1, 'Job Book Checklist', 'both', 0, 'document', 1, null, true, false, 'Generated by the application from live status; carries no weight.'),
    (v_facility_tpl, '2', 2, 'Facility / Flow Line Overview', 'both', 3, 'document', 2, null, true, false, 'Drawing set — original plus redline.'),
    (v_facility_tpl, '3', 3, 'Noble Energy Piping Specification', 'both', 1, 'document', 1, null, true, false, 'Current revision.'),
    (v_facility_tpl, '4', 4, 'Welding Procedure Specification (WPS)', 'both', 0.5, 'document', 1, null, true, false, null),
    (v_facility_tpl, '5', 5, 'Welding Procedure Qualification Record (PQR)', 'both', 0.5, 'document', 1, null, true, false, null),
    (v_facility_tpl, '6', 6, 'Welder Performance Qualifications (WPQ)', 'both', 6, 'personnel_certs', 1, 'welder', true, false, null),
    (v_facility_tpl, '7', 7, 'Certified Welding Inspector Credentials', 'both', 2, 'personnel_certs', 1, 'cwi', true, false, null),
    (v_facility_tpl, '8', 8, 'Non-Destructive Testing Technician Credentials', 'both', 3, 'personnel_certs', 1, 'ndt_technician', true, false, null),
    (v_facility_tpl, '9', 9, 'Non-Destructive Testing Procedures', 'both', 2, 'document', 4, null, true, false, 'One procedure per method in use: MT, PT, RT, UT.'),
    (v_facility_tpl, '10', 10, 'NDT Job Logs and Films', 'both', 10, 'records', 1, 'nde_report', true, false, 'Films provided separately.'),
    (v_facility_tpl, '11', 11, 'Weld Log Overview Sheet with Inspection Percentages (Noble Template)', 'both', 0, 'derived', 1, 'weld', true, false, 'Rolls up section 12; never scored independently.'),
    (v_facility_tpl, '12', 12, 'Detailed Weld Log (Noble Template)', 'both', 20, 'records', 1, 'weld', true, false, null),
    (v_facility_tpl, '13', 13, 'Torque Wrench Calibration Certificates', 'both', 5, 'equipment_certs', 1, 'torque_wrench', true, false, null),
    (v_facility_tpl, '14', 14, 'Detailed Torque Log (Noble Template)', 'both', 12, 'records', 1, 'torque_connection', true, false, null),
    (v_facility_tpl, '15', 15, 'Material Test Reports', 'both', 15, 'records', 1, 'material_heat', true, false, 'One MTR per heat number referenced by any weld.'),
    (v_facility_tpl, '16', 16, 'Pressure Testing Procedure with P&ID Valve Orientation', 'both', 1, 'document', 1, null, true, false, null),
    (v_facility_tpl, '17', 17, 'Pressure Testing Results with Recorder Calibration Certificates', 'both', 8, 'records', 1, 'pressure_test', true, false, null),
    (v_facility_tpl, '18', 18, 'Cathodic Protection Testing Locations and Baseline Results', 'both', 5, 'records', 1, 'cp_test_point', true, false, null),
    (v_facility_tpl, '19', 19, 'Ultrasonic Testing Locations and Baseline Results', 'facility', 2, 'records', 1, 'ut_reading', true, false, null),
    (v_facility_tpl, '20', 20, 'As-Built P&IDs', 'facility', 2, 'document', 1, null, true, false, null),
    (v_facility_tpl, '21', 21, 'Isometric Weld and X-Ray Map', 'facility', 1, 'document', 1, null, true, false, null),
    (v_facility_tpl, '22', 22, 'Isometric Heat Number and Torque Map', 'facility', 1, 'document', 1, null, true, false, null),
    (v_facility_tpl, 'S1', 23, 'Flexpipe Daily Field Reports', 'both', 0, 'supplemental', 1, null, false, true, 'Delivered in DP452; appears on no checklist revision.');
end $$;
